# Configuración de Streamlit para Progol Optimizer
# Solo opciones válidas para versiones recientes de Streamlit

[global]
# Configuración global
developmentMode = false

[server]
# Configuración del servidor
port = 8501
headless = true

[theme]
# Tema personalizado para la aplicación
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
# Configuración del navegador
gatherUsageStats = false

[logger]
# Configuración de logging
level = "info"